
export const keys = [
  "emulsifying",
  "solvent",
  "diluent",
  "stabilizing",
  "suspending",
  "binder",
  "disintegrant",
  "viscosity-increasing",
  "thickener",
  "sweetening",
  "acidifying",
  "plasticizer",
  "suppository base",
  "sustained/extended/control",
  "therapeutic agent",
  "skin penetrant",
  "bioabsorbable",
  "biocompatible",
  "biodegradable",
  "oleaginous vehicle",
  "antioxidant",
  "vaccine adjuvant",
  "adsorbent",
  "dispersing (solid)",
  "gelling agent",
  "opacifier",
  "alkalizing",
  "film-former/coating",
  "enteric coating",
  "humectant",
  "antimicrobial preservative",
  "antiseptic",
  "disinfectant",
  "solubilizing",
  "wetting agent",
  "buffering",
  "dietary supplement",
  "lubricant (glidant)",
  "anticaking",
  "bioadhesive",
  "release-modifying",
  "aerosol propellant",
  "air displacement",
  "water-absorbing",
  "water-repelling agent",
  "stiffening agent",
  "cationic_surfactant",
  "anionic",
  "mucoadhesive",
  "flavor enhancer",
  "chelating",
  "colorants",
  "granulating",
  "alcohol denaturant",
  "tonicity agent",
  "antifoaming",
  "penetration enhancer",
  "chelating agent",
  "taste masking",
  "fixative",
  "membrane",
  "transdermal backing",
  "dissolution enhancer",
  "nonionic surfactant",
  "cosmetic ingredient",
  "diagnostic aid",
  "acidulant",
  "directly compressible tableting excipient",
  "lyophilization aid",
  "ointment base",
  "food additive",
  "surfactant",
  "antiadherent",
  "antacid",
  "organic base",
  "color dispersant",
  "complexing agent",
  "gas forming",
  "sequestering_agent",
  "sterilizing_agent",
  "esterifying_agent",
  "water-miscible cosolvent",
  "crystallization modifier/inhibitor (sucrose)",
  "stabilizer for freeze-dried formulations",
  "blood substitute stabilizer",
  "channeling agent",
  "osmotic agent",
  "porosity modifier",
  "blood anticoagulant",
  "detergent",
  "water-holding",
  "cooling agent",
  "pigment",
  "polishing agent",
];

export const props = {
  data: [
    {
      title: "Acacia",
      props: [
        "Emulsifying",
        "Stabilizing",
        "Suspending",
        "Binder",
        "Viscosity-increasing",
        "Thickener",
      ],
    },
    {
      title: "Acesulfame Potassium",
      props: ["Sweetening"],
    },
    { title: "Acetic Acid, Glacial", props: ["Acidifying"] },
    { title: "Acetone", props: ["Solvent"] },
    { title: "Acetyltributyl Citrate", props: ["Plasticizer"] },
    {
      title: "Agar",
      props: [
        "Emulsifying",
        "Stabilizing",
        "Suspending",
        "Binder",
        "Viscosity-increasing",
        "Thickener",
        "Suppository base",
        "Sustained/Extended/Control",
      ],
    },
    { title: "Albumin", props: ["Stabilizing", "Therapeutic agent"] },
    {
      title: "Alcohol",
      props: [
        "Solvent",
        "Skin penetrant",
        "Antimicrobial preservative",
        "Disinfectant",
      ],
    },
    {
      title: "Alginic Acid",
      props: [
        "Stabilizing",
        "Suspending",
        "Binder",
        "Disintegrant",
        "Viscosity-increasing",
        "Sustained/Extended/Control",
      ],
    },
    {
      title: "Aliphatic Polyesters",
      props: ["Bioabsorbable", "Biocompatible", "Biodegradable"],
    },
    { title: "Alitame", props: ["Sweetening"] },
    {
      title: "Almond Oil",
      props: ["Emulsifying", "Solvent", "Oleaginous vehicle"],
    },
    { title: "Alpha Tocopherol", props: ["Therapeutic agent", "Antioxidant"] },
    {
      title: "Aluminum Hydroxide Adjuvant",
      props: ["Vaccine adjuvant", "Adsorbent"],
    },
    { title: "Aluminum Oxide ", props: ["Adsorbent", "Dispersing (Solid)"] },
    {
      title: "Aluminum Phosphate Adjuvant",
      props: ["Vaccine adjuvant", "Adsorbent"],
    },
    {
      title: "Aluminum Stearate",
      props: ["Emulsifying", "Stabilizing", "Gelling agent", "Opacifier"],
    },
    { title: "Ammonia Solution", props: ["Alkalizing"] },
    {
      title: "Ammonium Alginate",
      props: [
        "Emulsifying",
        "Diluent",
        "Stabilizing",
        "Thickener",
        "Film-former/coating",
        "Humectant",
      ],
    },
    { title: "Ascorbic Acid", props: ["Therapeutic agent", "Antioxidant"] },
    { title: "Ascorbyl Palmitate", props: ["Antioxidant"] },
    { title: "Aspartame", props: ["Sweetening"] },
    { title: "Attapulgite", props: ["Adsorbent"] },
    {
      title: "Bentonite",
      props: ["Stabilizing", "Suspending", "Viscosity-increasing", "Adsorbent"],
    },
    {
      title: "Benzalkonium Chloride",
      props: ["Therapeutic agent", "Antimicrobial preservative"],
    },
    {
      title: "Benzoic Acid",
      props: ["Therapeutic agent", "Antimicrobial preservative"],
    },
    {
      title: "Benzyl Alcohol",
      props: ["Antimicrobial preservative", "Disinfectant"],
    },
    {
      title: "Benzyl Benzoate",
      props: ["Solvent", "Plasticizer", "Therapeutic agent", "Solubilizing"],
    },
    { title: "Boric Acid", props: ["Antimicrobial preservative"] },
    { title: "Bronopol", props: ["Antimicrobial preservative", "Antiseptic"] },
    { title: "Butylated Hydroxyanisole", props: ["Antioxidant"] },
    { title: "Butylated Hydroxytoluene", props: ["Antioxidant"] },
    { title: "Butylparaben", props: ["Antimicrobial preservative"] },
    {
      title: "Calcium Alginate",
      props: [
        "Emulsifying",
        "Stabilizing",
        "Disintegrant",
        "Thickener",
        "Sustained/Extended/Control",
      ],
    },
    {
      title: "Calcium Carbonate",
      props: [
        "Diluent",
        "Therapeutic agent",
        "Opacifier",
        "Film-former/coating",
        "Buffering",
      ],
    },
    {
      title: "Calcium Phosphate, Dibasic Anhydrous",
      props: [
        "Diluent",
        "Buffering",
        "Dietary supplement",
        "Lubricant (glidant)",
        "Anticaking",
      ],
    },
    { title: "Calcium Phosphate, Dibasic Dihydrate", props: ["Diluent"] },
    { title: "Calcium Phosphate, Tribasic", props: ["Diluent"] },
    { title: "Calcium Stearate", props: ["Lubricant (glidant)"] },
    { title: "Calcium Sulfate", props: ["Diluent", "Disintegrant"] },
    {
      title: "Canola Oil",
      props: ["Oleaginous vehicle", "Lubricant (glidant)"],
    },
    {
      title: "Carbomer",
      props: [
        "Emulsifying",
        "Suspending",
        "Binder",
        "Viscosity-increasing",
        "Bioadhesive",
        "Release-modifying",
      ],
    },
    {
      title: "Carbon Dioxide",
      props: ["Aerosol propellant", "Air displacement"],
    },
    {
      title: "Carboxymethylcellulose Calcium",
      props: [
        "Stabilizing",
        "Suspending",
        "Disintegrant",
        "Viscosity-increasing",
        "Water-absorbing",
      ],
    },
    {
      title: "Carboxymethylcellulose Sodium",
      props: [
        "Stabilizing",
        "Suspending",
        "Binder",
        "Disintegrant",
        "Viscosity-increasing",
        "Film-former/coating",
        "Water-absorbing",
      ],
    },
    {
      title: "Carrageenan",
      props: [
        "Emulsifying",
        "Stabilizing",
        "Suspending",
        "Viscosity-increasing",
        "Sustained/Extended/Control",
        "Gelling agent",
      ],
    },
    {
      title: "Castor Oil",
      props: ["Emulsifying", "Solvent", "Oleaginous vehicle"],
    },
    {
      title: "Castor Oil, Hydrogenated",
      props: [
        "Sustained/Extended/Control",
        "Lubricant (glidant)",
        "Stiffening agent",
      ],
    },
    {
      title: "Cellulose, Microcrystalline",
      props: ["Diluent", "Suspending", "Disintegrant", "Adsorbent"],
    },
    {
      title: "Cellulose, Powdered",
      props: [
        "Diluent",
        "Suspending",
        "Disintegrant",
        "Adsorbent",
        "Lubricant (glidant)",
      ],
    },
    { title: "Cellulose, Silicified Microcrystalline", props: ["Diluent"] },
    {
      title: "Cellulose Acetate",
      props: ["Diluent", "Sustained/Extended/Control", "Film-former/coating"],
    },
    { title: "Cellulose Acetate Phthalate", props: ["Film-former/coating"] },
    {
      title: "Ceratonia",
      props: [
        "Stabilizing",
        "Suspending",
        "Binder",
        "Viscosity-increasing",
        "Sustained/Extended/Control",
      ],
    },
    {
      title: "Cetostearyl Alcohol",
      props: [
        "Antimicrobial preservative",
        "Antiseptic",
        "Disinfectant",
        "Cationic surfactant",
      ],
    },
    { title: "Cetrimide", props: ["Emulsifying", "Viscosity-increasing"] },
    {
      title: "Cetyl Alcohol",
      props: ["Emulsifying", "Film-former/coating", "Stiffening agent"],
    },
    {
      title: "Cetylpyridinium Chloride",
      props: [
        "Antimicrobial preservative",
        "Antiseptic",
        "Disinfectant",
        "Solubilizing",
        "Wetting agent",
        "Cationic surfactant",
      ],
    },
    {
      title: "Chitosan",
      props: [
        "Binder",
        "Disintegrant",
        "Viscosity-increasing",
        "Film-former/coating",
        "Mucoadhesive",
      ],
    },
    {
      title: "Chlorhexidine",
      props: ["Antimicrobial preservative", "Antiseptic"],
    },
    {
      title: "Chlorobutanol",
      props: ["Plasticizer", "Antimicrobial preservative"],
    },
    {
      title: "Chlorocresol",
      props: ["Antimicrobial preservative", "Disinfectant"],
    },
    { title: "Chlorodifluoroethane (HCFC)", props: ["Aerosol propellant"] },
    { title: "Chlorofluorocarbons (CFC)", props: ["Aerosol propellant"] },
    {
      title: "Chloroxylenol",
      props: ["Antimicrobial preservative", "Antiseptic", "Disinfectant"],
    },
    { title: "Cholesterol", props: ["Emulsifying"] },
    {
      title: "Citric Acid Monohydrate",
      props: [
        "Acidifying",
        "Antioxidant",
        "Buffering",
        "Chelating",
        "Flavor enhancer",
      ],
    },
    {
      title: "Colloidal Silicon Dioxide",
      props: [
        "Emulsifying",
        "Stabilizing",
        "Suspending",
        "Disintegrant",
        "Viscosity-increasing",
        "Adsorbent",
        "Lubricant (glidant)",
        "Anticaking",
      ],
    },
    { title: "Coloring Agents", props: ["Opacifier", "Colorants"] },
    {
      title: "Copovidone",
      props: ["Binder", "Film-former/coating", "Granulating"],
    },
    { title: "Corn Oil", props: ["Solvent", "Oleaginous vehicle"] },
    { title: "Cottonseed Oil", props: ["Solvent", "Oleaginous vehicle"] },
    { title: "Cresol", props: ["Antimicrobial preservative", "Disinfectant"] },
    { title: "Croscarmellose Sodium", props: ["Disintegrant"] },
    { title: "Crospovidone", props: ["Disintegrant"] },
    { title: "Cyclodextrins", props: ["Stabilizing", "Solubilizing"] },
    {
      title: "Cyclomethicone",
      props: ["Emulsifying", "Viscosity-increasing", "Humectant"],
    },
    {
      title: "Denatonium Benzoate",
      props: ["Flavor enhancer", "Alcohol denaturant"],
    },
    { title: "Dextrates", props: ["Diluent", "Binder"] },
    {
      title: "Dextrin",
      props: ["Diluent", "Suspending", "Binder", "Stiffening agent"],
    },
    {
      title: "Dextrose",
      props: ["Diluent", "Sweetening", "Therapeutic agent", "Tonicity agent"],
    },
    {
      title: "Dibutyl Phthalate",
      props: ["Solvent", "Plasticizer", "Film-former/coating"],
    },
    { title: "Dibutyl Sebacate", props: ["Plasticizer"] },
    { title: "Diethanolamine", props: ["Emulsifying", "Alkalizing"] },
    {
      title: "Diethyl Phthalate",
      props: ["Solvent", "Plasticizer", "Film-former/coating"],
    },
    { title: "Difluoroethane (HFC)", props: ["Aerosol propellant"] },
    { title: "Dimethicone", props: ["Emulsifying", "Antifoaming"] },
    { title: "Dimethyl Ether", props: ["Aerosol propellant"] },
    {
      title: "Dimethyl Phthalate",
      props: ["Solvent", "Plasticizer", "Film-former/coating"],
    },
    { title: "Dimethyl Sulfoxide", props: ["Solvent", "Penetration enhancer"] },
    { title: "Dimethylacetamide", props: ["Solvent"] },
    { title: "Disodium Edetate", props: ["Chelating agent"] },
    { title: "Docusate Sodium", props: ["Wetting agent", "Anionic"] },
    { title: "Edetic Acid", props: ["Chelating"] },
    { title: "Erythorbic Acid", props: ["Antioxidant"] },
    { title: "Erythritol", props: ["Diluent", "Sweetening", "Taste masking"] },
    { title: "Ethyl Acetate", props: ["Solvent", "Flavor enhancer"] },
    {
      title: "Ethyl Lactate",
      props: ["Solvent", "Film-former/coating", "Flavor enhancer"],
    },
    {
      title: "Ethyl Maltol",
      props: ["Solvent", "Oleaginous vehicle", "Flavor enhancer"],
    },
    { title: "Ethyl Oleate", props: ["Flavor enhancer"] },
    { title: "Ethyl Vanillin", props: ["Flavor enhancer"] },
    {
      title: "Ethylcellulose",
      props: [
        "Diluent",
        "Binder",
        "Viscosity-increasing",
        "Film-former/coating",
        "Fixative",
      ],
    },
    {
      title: "Ethylene Glycol Palmitostearate",
      props: ["Emulsifying", "Stabilizing"],
    },
    {
      title: "Ethylene Vinyl Acetate",
      props: ["Membrane", "Transdermal backing"],
    },
    { title: "Ethylparaben", props: ["Antimicrobial preservative"] },
    {
      title: "Fructose",
      props: [
        "Diluent",
        "Sweetening",
        "Flavor enhancer",
        "Dissolution enhancer",
      ],
    },
    {
      title: "Fumaric Acid",
      props: [
        "Acidifying",
        "Therapeutic agent",
        "Antioxidant",
        "Flavor enhancer",
      ],
    },
    {
      title: "Gelatin",
      props: [
        "Suspending",
        "Binder",
        "Viscosity-increasing",
        "Gelling agent",
        "Film-former/coating",
      ],
    },
    {
      title: "Glucose, Liquid",
      props: ["Binder", "Sweetening", "Film-former/coating"],
    },
    {
      title: "Glycerin",
      props: [
        "Emulsifying",
        "Sweetening",
        "Solvent",
        "Plasticizer",
        "Humectant",
        "Antimicrobial preservative",
        "Tonicity agent",
      ],
    },
    {
      title: "Glyceryl Behenate",
      props: ["Binder", "Film-former/coating", "Lubricant (glidant)"],
    },
    {
      title: "Glyceryl Monooleate",
      props: [
        "Emulsifying",
        "Stabilizing",
        "Sustained/Extended/Control",
        "Gelling agent",
        "Bioadhesive",
        "Mucoadhesive",
        "Nonionic surfactant",
      ],
    },
    {
      title: "Glyceryl Monostearate",
      props: [
        "Emulsifying",
        "Stabilizing",
        "Sustained/Extended/Control",
        "Solubilizing",
        "Lubricant (glidant)",
      ],
    },
    {
      title: "Glyceryl Palmitostearate",
      props: [
        "Diluent",
        "Sustained/Extended/Control",
        "Biodegradable",
        "Gelling agent",
        "Film-former/coating",
        "Lubricant (glidant)",
        "Release-modifying",
        "Taste masking",
      ],
    },
    { title: "Glycofurol", props: ["Solvent", "Penetration enhancer"] },
    {
      title: "Guar Gum",
      props: ["Suspending", "Binder", "Disintegrant", "Viscosity-increasing"],
    },
    {
      title: "Hectorite",
      props: [
        "Emulsifying",
        "Viscosity-increasing",
        "Adsorbent",
        "Cosmetic ingredient",
      ],
    },
    { title: "Heptafluoropropane (HFC)", props: ["Aerosol propellant"] },
    {
      title: "Hexetidine",
      props: ["Antimicrobial preservative", "Antiseptic"],
    },
    { title: "Hydrocarbons (HC)", props: ["Aerosol propellant"] },
    { title: "Hydrochloric Acid", props: ["Acidifying"] },
    {
      title: "Hydroxyethyl Cellulose",
      props: [
        "Suspending",
        "Binder",
        "Viscosity-increasing",
        "Thickener",
        "Film-former/coating",
        "Lubricant (glidant)",
      ],
    },
    {
      title: "Hydroxyethylmethyl Cellulose",
      props: [
        "Suspending",
        "Binder",
        "Viscosity-increasing",
        "Thickener",
        "Film-former/coating",
      ],
    },
    {
      title: "Hydroxypropyl Cellulose",
      props: [
        "Emulsifying",
        "Stabilizing",
        "Suspending",
        "Binder",
        "Viscosity-increasing",
        "Thickener",
        "Sustained/Extended/Control",
        "Film-former/coating",
      ],
    },
    {
      title: "Hydroxypropyl Cellulose, Low-substituted",
      props: ["Binder", "Disintegrant"],
    },
    {
      title: "Hydroxypropyl Starch",
      props: [
        "Emulsifying",
        "Binder",
        "Disintegrant",
        "Viscosity-increasing",
        "Thickener",
      ],
    },
    {
      title: "Hypromellose",
      props: [
        "Stabilizing",
        "Suspending",
        "Binder",
        "Viscosity-increasing",
        "Sustained/Extended/Control",
        "Film-former/coating",
      ],
    },
    {
      title: "Hypromellose Acetate Succinate",
      props: [
        "Sustained/Extended/Control",
        "Dispersing (Solid)",
        "Film-former/coating",
        "Enteric coating",
      ],
    },
    { title: "Hypromellose Phthalate", props: ["Film-former/coating"] },
    { title: "Imidurea", props: ["Antimicrobial preservative"] },
    { title: "Inulin", props: ["Binder", "Sweetening", "Diagnostic aid"] },
    { title: "Iron Oxides", props: ["Colorants"] },
    {
      title: "Isomalt",
      props: ["Diluent", "Sweetening", "Film-former/coating", "Granulating"],
    },
    { title: "Isopropyl Alcohol", props: ["Solvent", "Disinfectant"] },
    {
      title: "Isopropyl Myristate",
      props: ["Emulsifying", "Solvent", "Skin penetrant", "Oleaginous vehicle"],
    },
    {
      title: "Isopropyl Palmitate",
      props: ["Emulsifying", "Solvent", "Skin penetrant", "Oleaginous vehicle"],
    },
    { title: "Kaolin", props: ["Diluent", "Suspending", "Adsorbent"] },
    { title: "Lactic Acid", props: ["Acidifying", "Acidulant"] },
    {
      title: "Lactitol",
      props: ["Diluent", "Sweetening", "Therapeutic agent"],
    },
    {
      title: "Lactose, Anhydrous",
      props: [
        "Diluent",
        "Binder",
        "Directly compressible tableting excipient",
        "Lyophilization aid",
      ],
    },
    { title: "Lactose, Monohydrate", props: ["Diluent", "Binder"] },
    {
      title: "Lactose, Spray-Dried",
      props: [
        "Diluent",
        "Binder",
        "Sweetening",
        "Directly compressible tableting excipient",
      ],
    },
    { title: "Lanolin", props: ["Emulsifying", "Ointment base"] },
    { title: "Lanolin Alcohols", props: ["Emulsifying", "Ointment base"] },
    { title: "Lanolin, Hydrous", props: ["Emulsifying", "Ointment base"] },
    {
      title: "Lauric Acid",
      props: [
        "Emulsifying",
        "Lubricant (glidant)",
        "Food additive",
        "Surfactant",
      ],
    },
    { title: "Lecithin", props: ["Emulsifying", "Solubilizing"] },
    {
      title: "Leucine",
      props: [
        "Emulsifying",
        "Lubricant (glidant)",
        "Flavor enhancer",
        "Antiadherent",
      ],
    },

    {
      title: "Linoleic Acid",
      props: ["Emulsifying", "Skin penetrant", "Dietary supplement"],
    },
    {
      title: "Macrogol 15 Hydroxystearate",
      props: ["Solubilizing", "Dissolution enhancer", "Nonionic surfactant"],
    },
    {
      title: "Magnesium Aluminum Silicate",
      props: [
        "Stabilizing",
        "Suspending",
        "Binder",
        "Disintegrant",
        "Viscosity-increasing",
        "Adsorbent",
      ],
    },
    {
      title: "Magnesium Carbonate",
      props: ["Emulsifying", "Diluent", "Lubricant (glidant)", "Anticaking"],
    },
    { title: "Magnesium Oxide", props: ["Diluent", "Adsorbent", "Antacid"] },
    {
      title: "Magnesium Silicate",
      props: ["Lubricant (glidant)", "Anticaking"],
    },
    { title: "Magnesium Stearate", props: ["Lubricant (glidant)"] },
    {
      title: "Magnesium Trisilicate",
      props: ["Therapeutic agent", "Lubricant (glidant)", "Anticaking"],
    },
    {
      title: "Malic Acid",
      props: [
        "Therapeutic agent",
        "Antioxidant",
        "Buffering",
        "Chelating",
        "Flavor enhancer",
        "Chelating agent",
        "Acidulant",
      ],
    },
    { title: "Maltitol", props: [] },

    { title: "Maltitol Solution", props: ["Suspending", "Sweetening"] },
    {
      title: "Maltodextrin",
      props: [
        "Diluent",
        "Binder",
        "Viscosity-increasing",
        "Film-former/coating",
      ],
    },
    { title: "Maltol", props: ["Flavor enhancer"] },
    { title: "Maltose", props: ["Diluent", "Sweetening"] },
    { title: "Mannitol", props: ["Diluent", "Sweetening", "Tonicity agent"] },
    {
      title: "Medium-chain Triglycerides",
      props: ["Emulsifying", "Suspending", "Solvent", "Therapeutic agent"],
    },
    { title: "Meglumine", props: ["Solubilizing", "Organic base"] },
    { title: "Menthol", props: ["Therapeutic agent", "Flavor enhancer"] },
    {
      title: "Methylcellulose",
      props: [
        "Emulsifying",
        "Suspending",
        "Binder",
        "Disintegrant",
        "Viscosity-increasing",
        "Film-former/coating",
      ],
    },
    { title: "Methylparaben", props: ["Antimicrobial preservative"] },
    {
      title: "Mineral Oil",
      props: [
        "Emulsifying",
        "Solvent",
        "Oleaginous vehicle",
        "Lubricant (glidant)",
      ],
    },
    {
      title: "Mineral Oil, Light",
      props: [
        "Emulsifying",
        "Solvent",
        "Therapeutic agent",
        "Skin penetrant",
        "Oleaginous vehicle",
        "Lubricant (glidant)",
        "Penetration enhancer",
      ],
    },
    {
      title: "Mineral Oil and Lanolin Alcohols",
      props: ["Emulsifying", "Plasticizer"],
    },
    {
      title: "Monoethanolamine",
      props: [
        "Emulsifying",
        "Stabilizing",
        "Solvent",
        "Therapeutic agent",
        "Alkalizing",
      ],
    },
    { title: "Monosodium Glutamate", props: ["Buffering", "Flavor enhancer"] },
    {
      title: "Monothioglycerol",
      props: ["Antioxidant", "Antimicrobial preservative"],
    },
    {
      title: "Myristic Acid",
      props: ["Emulsifying", "Skin penetrant", "Lubricant (glidant)"],
    },
    {
      title: "Neohesperidin Dihydrochalcone",
      props: ["Sweetening", "Flavor enhancer"],
    },
    { title: "Nitrogen", props: ["Aerosol propellant", "Air displacement"] },
    {
      title: "Nitrous Oxide",
      props: ["Therapeutic agent", "Aerosol propellant"],
    },
    {
      title: "Octyldodecanol",
      props: ["Emulsifying", "Thickener", "Solvent", "Lubricant (glidant)"],
    },
    { title: "Oleic Acid", props: ["Emulsifying", "Skin penetrant"] },
    {
      title: "Oleyl Alcohol",
      props: [
        "Emulsifying",
        "Sustained/Extended/Control",
        "Skin penetrant",
        "Antifoaming",
        "Dissolution enhancer",
      ],
    },
    { title: "Olive Oil", props: ["Oleaginous vehicle"] },
    {
      title: "Palmitic Acid",
      props: [
        "Emulsifying",
        "Sustained/Extended/Control",
        "Skin penetrant",
        "Lubricant (glidant)",
      ],
    },
    {
      title: "Paraffin",
      props: ["Film-former/coating", "Stiffening agent", "Ointment base"],
    },
    { title: "Peanut Oil", props: ["Solvent", "Oleaginous vehicle"] },
    {
      title: "Pectin",
      props: [
        "Emulsifying",
        "Stabilizing",
        "Thickener",
        "Adsorbent",
        "Gelling agent",
      ],
    },
    { title: "Petrolatum", props: ["Emulsifying", "Ointment base"] },
    {
      title: "Petrolatum and Lanolin Alcohols",
      props: ["Emulsifying", "Plasticizer", "Ointment base"],
    },
    {
      title: "Phenol",
      props: [
        "Therapeutic agent",
        "Antimicrobial preservative",
        "Antiseptic",
        "Disinfectant",
      ],
    },
    {
      title: "Phenoxyethanol",
      props: ["Antimicrobial preservative", "Disinfectant"],
    },
    { title: "Phenylethyl Alcohol", props: ["Antimicrobial preservative"] },
    {
      title: "Phenylmercuric Acetate",
      props: ["Antimicrobial preservative", "Antiseptic"],
    },
    {
      title: "Phenylmercuric Borate",
      props: ["Antimicrobial preservative", "Antiseptic"],
    },
    {
      title: "Phenylmercuric Nitrate",
      props: ["Antimicrobial preservative", "Antiseptic"],
    },
    { title: "Phosphoric Acid", props: ["Acidifying"] },
    { title: "Polacrilin Potassium", props: ["Disintegrant"] },
    {
      title: "Poloxamer",
      props: [
        "Emulsifying",
        "Dispersing (Solid)",
        "Solubilizing",
        "Wetting agent",
        "Lubricant (glidant)",
      ],
    },
    {
      title: "Polycarbophil",
      props: [
        "Emulsifying",
        "Suspending",
        "Binder",
        "Thickener",
        "Sustained/Extended/Control",
        "Adsorbent",
        "Bioadhesive",
      ],
    },

    {
      title: "Polydextrose",
      props: [
        "Binder",
        "Viscosity-increasing",
        "Film-former/coating",
        "Granulating",
      ],
    },
    {
      title: "Polyethylene Glycol",
      props: [
        "Solvent",
        "Plasticizer",
        "Suppository base",
        "Lubricant (glidant)",
        "Ointment base",
      ],
    },
    {
      title: "Polyethylene Oxide",
      props: ["Binder", "Thickener", "Mucoadhesive"],
    },
    {
      title: "Polymethacrylates",
      props: [
        "Diluent",
        "Binder",
        "Sustained/Extended/Control",
        "Film-former/coating",
        "Enteric coating",
      ],
    },
    {
      title: "Poly(methyl vinyl ether/maleic anhydride)",
      props: [
        "Emulsifying",
        "Stabilizing",
        "Viscosity-increasing",
        "Sustained/Extended/Control",
        "Film-former/coating",
        "Enteric coating",
        "Bioadhesive",
        "Release-modifying",
        "Color dispersant",
        "Complexing agent",
      ],
    },
    {
      title: "Polyoxyethylene Alkyl Ethers",
      props: [
        "Emulsifying",
        "Gelling agent",
        "Solubilizing",
        "Wetting agent",
        "Penetration enhancer",
      ],
    },
    {
      title: "Polyoxyethylene Castor Oil Derivatives",
      props: ["Emulsifying", "Solubilizing", "Wetting agent"],
    },
    {
      title: "Polyoxyethylene Sorbitan Fatty Acid Esters",
      props: [
        "Emulsifying",
        "Suspending",
        "Solubilizing",
        "Wetting agent",
        "Nonionic surfactant",
      ],
    },
    {
      title: "Polyoxyethylene Stearates",
      props: ["Emulsifying", "Solubilizing", "Wetting agent"],
    },
    {
      title: "Polyvinyl Acetate Phthalate",
      props: ["Film-former/coating", "Enteric coating"],
    },
    {
      title: "Polyvinyl Alcohol",
      props: [
        "Stabilizing",
        "Viscosity-increasing",
        "Film-former/coating",
        "Lubricant (glidant)",
      ],
    },
    {
      title: "Potassium Alginate",
      props: ["Emulsifying", "Stabilizing", "Suspending", "Thickener"],
    },
    {
      title: "Potassium Benzoate",
      props: [
        "Therapeutic agent",
        "Antimicrobial preservative",
        "Lubricant (glidant)",
      ],
    },
    {
      title: "Potassium Bicarbonate",
      props: ["Therapeutic agent", "Alkalizing", "Gas forming"],
    },
    {
      title: "Potassium Chloride",
      props: [
        "Stabilizing",
        "Thickener",
        "Sustained/Extended/Control",
        "Therapeutic agent",
        "Gelling agent",
        "Tonicity agent",
      ],
    },
    {
      title: "Potassium Citrate",
      props: [
        "Therapeutic agent",
        "Alkalizing",
        "Buffering",
        "Sequestering agent",
      ],
    },
    {
      title: "Potassium Hydroxide",
      props: ["Therapeutic agent", "Alkalizing"],
    },
    {
      title: "Potassium Metabisulfite",
      props: ["Antioxidant", "Antimicrobial preservative", "Sterilizing agent"],
    },
    { title: "Potassium Sorbate", props: ["Antimicrobial preservative"] },
    {
      title: "Povidone",
      props: ["Suspending", "Binder", "Disintegrant", "Dissolution enhancer"],
    },

    {
      title: "Propionic Acid",
      props: [
        "Acidifying",
        "Antioxidant",
        "Antimicrobial preservative",
        "Esterifying agent",
      ],
    },
    { title: "Propyl Gallate", props: ["Antioxidant"] },
    { title: "Propylene Carbonate", props: ["Solvent", "Gelling agent"] },
    {
      title: "Propylene Glycol",
      props: [
        "Stabilizing",
        "Solvent",
        "Plasticizer",
        "Humectant",
        "Antimicrobial preservative",
        "Disinfectant",
        "Water-miscible cosolvent",
      ],
    },
    {
      title: "Propylene Glycol Alginate",
      props: [
        "Emulsifying",
        "Stabilizing",
        "Suspending",
        "Viscosity-increasing",
        "Gelling agent",
        "Flavor enhancer",
        "Antifoaming",
        "Taste masking",
      ],
    },
    { title: "Propylparaben", props: ["Antimicrobial preservative"] },
    {
      title: "Pyrrolidone",
      props: ["Solvent", "Plasticizer", "Solubilizing", "Penetration enhancer"],
    },
    {
      title: "Raffinose",
      props: [
        "Stabilizing",
        "Crystallization modifier/Inhibitor (sucrose)",
        "Stabilizer for freeze-dried formulations",
        "Blood substitute stabilizer",
      ],
    },
    {
      title: "Saccharin",
      props: ["Sweetening", "Flavor enhancer", "Taste masking"],
    },
    {
      title: "Saccharin Sodium",
      props: ["Sweetening", "Flavor enhancer", "Taste masking"],
    },
    {
      title: "Saponite",
      props: ["Emulsifying", "Suspending", "Viscosity-increasing", "Adsorbent"],
    },
    { title: "Sesame Oi", props: ["Solvent", "Oleaginous vehicle"] },
    { title: "Shellac", props: ["Film-former/coating", "Release-modifying"] },
    {
      title: "Simethicone",
      props: ["Diluent", "Water-repelling agent", "Antifoaming"],
    },
    {
      title: "Sodium Acetate",
      props: [
        "Stabilizing",
        "Therapeutic agent",
        "Antimicrobial preservative",
        "Buffering",
        "Flavor enhancer",
      ],
    },
    {
      title: "Sodium Alginate",
      props: [
        "Diluent",
        "Stabilizing",
        "Suspending",
        "Binder",
        "Disintegrant",
        "Viscosity-increasing",
        "Thickener",
        "Sustained/Extended/Control",
      ],
    },
    { title: "Sodium Ascorbate", props: ["Therapeutic agent", "Antioxidant"] },
    {
      title: "Sodium Benzoate",
      props: ["Antimicrobial preservative", "Lubricant (glidant)"],
    },
    {
      title: "Sodium Bicarbonate",
      props: ["Therapeutic agent", "Alkalizing", "Gas forming"],
    },
    {
      title: "Sodium Borate",
      props: [
        "Emulsifying",
        "Stabilizing",
        "Alkalizing",
        "Antimicrobial preservative",
        "Disinfectant",
        "Buffering",
      ],
    },
    {
      title: "Sodium Chloride",
      props: [
        "Diluent",
        "Lubricant (glidant)",
        "Tonicity agent",
        "Channeling agent",
        "Osmotic agent",
        "Porosity modifier",
      ],
    },
    {
      title: "Sodium Citrate Dihydrate",
      props: [
        "Emulsifying",
        "Therapeutic agent",
        "Alkalizing",
        "Buffering",
        "Sequestering agent",
        "Blood anticoagulant",
      ],
    },
    {
      title: "Sodium Cyclamate",
      props: ["Sweetening", "Flavor enhancer", "Taste masking"],
    },
    {
      title: "Sodium Hyaluronate",
      props: [
        "Sustained/Extended/Control",
        "Therapeutic agent",
        "Humectant",
        "Lubricant (glidant)",
      ],
    },
    { title: "Sodium Hydroxide", props: ["Alkalizing", "Buffering"] },
    {
      title: "Sodium Lactate",
      props: [
        "Emulsifying",
        "Therapeutic agent",
        "Humectant",
        "Antimicrobial preservative",
        "Buffering",
        "Flavor enhancer",
      ],
    },
    {
      title: "Sodium Lauryl Sulfate",
      props: [
        "Emulsifying",
        "Skin penetrant",
        "Wetting agent",
        "Lubricant (glidant)",
        "Anionic",
        "Detergent",
      ],
    },
    {
      title: "Sodium Metabisulfite",
      props: ["Antioxidant", "Antimicrobial preservative"],
    },
    {
      title: "Sodium Phosphate, Dibasic",
      props: [
        "Emulsifying",
        "Therapeutic agent",
        "Buffering",
        "Sequestering agent",
      ],
    },
    {
      title: "Sodium Phosphate, Monobasic",
      props: [
        "Emulsifying",
        "Therapeutic agent",
        "Buffering",
        "Sequestering agent",
      ],
    },
    {
      title: "Sodium Propionate",
      props: [
        "Therapeutic agent",
        "Antimicrobial preservative",
        "Flavor enhancer",
      ],
    },
    { title: "Sodium Starch Glycolate", props: ["Suspending", "Disintegrant"] },
    { title: "Sodium Stearyl Fumarate", props: ["Lubricant (glidant)"] },
    {
      title: "Sodium Sulfite",
      props: ["Antioxidant", "Antimicrobial preservative"],
    },
    { title: "Sorbic Acid", props: ["Antimicrobial preservative"] },
    {
      title: "Sorbitan Esters (Sorbitan Fatty Acid Esters)",
      props: [
        "Emulsifying",
        "Suspending",
        "Dispersing (Solid)",
        "Solubilizing",
        "Wetting agent",
        "Nonionic surfactant",
      ],
    },
    {
      title: "Sorbitol",
      props: [
        "Diluent",
        "Sweetening",
        "Plasticizer",
        "Therapeutic agent",
        "Humectant",
      ],
    },
    { title: "Soybean Oil", props: ["Solvent", "Oleaginous vehicle"] },
    {
      title: "Starch",
      props: [
        "Diluent",
        "Binder",
        "Disintegrant",
        "Therapeutic agent",
        "Lubricant (glidant)",
      ],
    },
    {
      title: "Starch, Pregelatinized",
      props: ["Diluent", "Binder", "Disintegrant"],
    },
    { title: "Starch, Sterilizable Maize", props: ["Lubricant (glidant)"] },
    {
      title: "Stearic Acid",
      props: ["Emulsifying", "Binder", "Solubilizing", "Lubricant (glidant)"],
    },
    {
      title: "Stearyl Alcohol",
      props: [
        "Emulsifying",
        "Stabilizing",
        "Viscosity-increasing",
        "Sustained/Extended/Control",
        "Skin penetrant",
        "Release-modifying",
        "Stiffening agent",
        "Penetration enhancer",
        "Water-holding",
      ],
    },
    { title: "Sucralose", props: ["Sweetening"] },
    {
      title: "Sucrose",
      props: [
        "Diluent",
        "Suspending",
        "Binder",
        "Viscosity-increasing",
        "Sweetening",
        "Film-former/coating",
        "Granulating",
      ],
    },
    {
      title: "Sugar, Compressible",
      props: ["Diluent", "Binder", "Sweetening"],
    },
    {
      title: "Sugar, Confectioner’s",
      props: ["Diluent", "Binder", "Sweetening", "Film-former/coating"],
    },
    { title: "Sugar Spheres", props: ["Diluent"] },
    {
      title: "Sulfobutylether b-Cyclodextrin",
      props: [
        "Diluent",
        "Stabilizing",
        "Viscosity-increasing",
        "Solubilizing",
        "Dissolution enhancer",
        "Osmotic agent",
      ],
    },
    { title: "Sulfuric Acid", props: ["Acidifying"] },
    {
      title: "Sunflower Oil",
      props: [
        "Emulsifying",
        "Diluent",
        "Binder",
        "Solvent",
        "Therapeutic agent",
      ],
    },
    {
      title: "Suppository Bases, Hard Fat (Hard fat triglyceride esters)",
      props: ["Suppository base"],
    },
    { title: "Talc", props: ["Diluent", "Lubricant (glidant)", "Anticaking"] },
    {
      title: "Tartaric Acid",
      props: [
        "Acidifying",
        "Antioxidant",
        "Flavor enhancer",
        "Sequestering agent",
      ],
    },
    { title: "Tetrafluoroethane (HFC)", props: ["Aerosol propellant"] },
    { title: "Thaumatin", props: ["Sweetening", "Flavor enhancer"] },
    {
      title: "Thimerosal",
      props: ["Therapeutic agent", "Antimicrobial preservative", "Antiseptic"],
    },
    {
      title: "Thymol",
      props: [
        "Therapeutic agent",
        "Skin penetrant",
        "Antioxidant",
        "Antimicrobial preservative",
        "Antiseptic",
        "Disinfectant",
        "Flavor enhancer",
        "Cooling agent",
      ],
    },
    {
      title: "Titanium Dioxide",
      props: ["Opacifier", "Film-former/coating", "Pigment"],
    },
    {
      title: "Tragacanth",
      props: ["Emulsifying", "Suspending", "Viscosity-increasing"],
    },
    {
      title: "Trehalose",
      props: [
        "Diluent",
        "Stabilizing",
        "Thickener",
        "Sweetening",
        "Humectant",
        "Flavor enhancer",
        "Colorants",
        "Stabilizer for freeze-dried formulations",
      ],
    },
    { title: "Triacetin", props: ["Solvent", "Plasticizer", "Humectant"] },
    { title: "Tributyl Citrat", props: ["Plasticizer"] },
    {
      title: "Triethanolamin",
      props: [
        "Emulsifying",
        "Solvent",
        "Plasticizer",
        "Alkalizing",
        "Humectant",
        "Buffering",
      ],
    },
    {
      title: "Triethyl Citrate",
      props: ["Solvent", "Plasticizer", "Flavor enhancer"],
    },
    {
      title: "Vanilli",
      props: ["Film-former/coating", "Flavor enhancer", "Taste masking"],
    },
    {
      title: "Vegetable Oil, Hydrogenated",
      props: ["Binder", "Sustained/Extended/Control", "Lubricant (glidant)"],
    },
    { title: "Water", props: ["Solvent"] },
    {
      title: "Wax, Anionic Emulsifying",
      props: ["Emulsifying", "Stiffening agent"],
    },
    { title: "Wax, Carnauba", props: ["Film-former/coating"] },
    { title: "Wax, Cetyl Esters", props: ["Emulsifying", "Stiffening agent"] },
    {
      title: "Wax, Microcrystalline",
      props: [
        "Sustained/Extended/Control",
        "Film-former/coating",
        "Stiffening agent",
      ],
    },
    {
      title: "Wax, Nonionic Emulsifying",
      props: ["Emulsifying", "Stiffening agent"],
    },
    {
      title: "Wax, White",
      props: [
        "Stabilizing",
        "Sustained/Extended/Control",
        "Film-former/coating",
        "Stiffening agent",
      ],
    },
    {
      title: "Wax, Yellow",
      props: [
        "Stabilizing",
        "Sustained/Extended/Control",
        "Stiffening agent",
        "Polishing agent",
      ],
    },
    {
      title: "Xanthan Gum",
      props: [
        "Emulsifying",
        "Stabilizing",
        "Suspending",
        "Viscosity-increasing",
        "Thickener",
      ],
    },
    {
      title: "Xylitol",
      props: [
        "Emulsifying",
        "Diluent",
        "Sweetening",
        "Film-former/coating",
        "Humectant",
        "Antimicrobial preservative",
      ],
    },
    {
      title: "Zein",
      props: ["Binder", "Sustained/Extended/Control", "Film-former/coating"],
    },
    {
      title: "Zinc Acetate",
      props: [
        "Emulsifying",
        "Stabilizing",
        "Therapeutic agent",
        "Gelling agent",
        "Opacifier",
      ],
    },
    {
      title: "Zinc Stearate",
      props: ["Thickener", "Opacifier", "Lubricant (glidant)"],
    },
  ],
};
