export const items = [
  {
    name: "Oxide",
    dec: [
      "Acid",
      " Disintegrant",
      " Sustained/Extended/Control",
      " Disintegrant",
      " Sustained/Extended/Control, ",
      " Disintegrant, ",
      " Sustained/Extended/Control, ",
      " Disintegrant, ",
      " Sustained/Extended/Control, ",
      " Disintegrant, ",
      " Sustained/Extended/Control, ",
    ],
  },
  {
    name: "Acid",
    dec: ["oxide", "Binder, ", "Stabilizing, ", "Disintegrant, "],
  },
  {
    name: "Polyesters",
    dec: [
      "Solubilizing",
      "Antiseptic",
      "Bioadhesive",
      "Sustained/Extended/Control",
    ],
  },
  {
    name: "Glacial",
    dec: ["Sustained/Extended/Control", "Sustained/Extended/Control "],
  },
  {
    name: "Oxide",
    dec: "Emulsifying Disintegrant Sustained/Extended/Control",
  },
  {
    name: "Acid",
    dec: "Binder Stabilizing Disintegrant",
  },
  {
    name: "Polyesters",
    dec: "Solubilizing Antiseptic Bioadhesive Sustained/Extended/Control ",
  },
  {
    name: "Glacial",
    dec: "Sustained/Extended/Control  Sustained/Extended/Control ",
  },
  {
    name: "Oxide",
    dec: "Emulsifying Disintegrant Sustained/Extended/Control",
  },
  {
    name: "Acid",
    dec: "Binder Stabilizing Disintegrant",
  },
  {
    name: "Polyesters",
    dec: "Solubilizing Antiseptic Bioadhesive Sustained/Extended/Control ",
  },
  {
    name: "Glacial",
    dec: "Sustained/Extended/Control  Sustained/Extended/Control ",
  },
];

export const drugsData = [
  {
    dec: "جستجو چیز",
    uri: require("../../assets/png/vec1.png"),
    bgc: "#DBDAF7",
    screen: "Plus",
    id: 1,
  },
  {
    dec: "جستجو ویژگی",
    uri: require("../../assets/png/vec2.png"),
    bgc: "#F6E3DB",
    screen: "Search",
    id: 2,
  },
  {
    dec: "توضیحات",
    uri: require("../../assets/png/vec3.png"),
    bgc: "#D8F3F1",
    screen: "Search",
    id: 3,
  },
  {
    dec: "تماس با ما",
    uri: require("../../assets/png/vec4.png"),
    bgc: "#D0EDFB",
    screen: "Notification",
    id: 4,
  },
];

export const keys = [
  "emulsifying",
  "solvent",
  "diluent",
  "stabilizing",
  "suspending",
  "binder",
  "disintegrant",
  "viscosity_increasing",
  "thickener",
  "sweetening",
  "acidifying",
  "plasticizer",
  "suppository_base",
  "sustained_extended_control",
  "therapeutic_agent",
  "skin_penetrant",
  "bioabsorbable",
  "biocompatible",
  "biodegradable",
  "oleaginous_vehicle",
  "antioxidant",
  "vaccine_adjuvant",
  "adsorbent",
  "dispersing_Solid",
  "gelling_agent",
  "opacifier",
  "alkalizing",
  "film_former_coating",
  "enteric_coating",
  "humectant",
  "antimicrobial_preservative",
  "antiseptic",
  "disinfectant",
  "solubilizing",
  "wetting_agent",
  "buffering",
  "dietary_supplement",
  "lubricant_glidant",
  "anticaking",
  "bioadhesive",
  "release_modifying",
  "aerosol_propellant",
  "air_displacement",
  "water_absorbing",
  "water_repelling_agent",
  "stiffening_agent",
  "cationic_surfactant",
  "anionic",
  "mucoadhesive",
  "flavor_enhancer",
  "chelating",
  "colorants",
  "granulating",
  "alcohol_denaturant",
  "tonicity_agent",
  "antifoaming",
  "Penetration_enhancer",
  "chelating_agent",
  "taste_masking",
  "fixative",
  "membrane",
  "transdermal_backing",
  "dissolution_enhancer",
  "nonionic_surfactant",
  "cosmetic_ingredient",
  "diagnostic_aid",
  "acidulant",
  "directly_compressible_tableting_excipient",
  "lyophilization_aid",
  "ointment_base",
  "food_additive",
  "surfactant",
  "antiadherent",
  "antacid",
  "organic_base",
  "color_dispersant",
  "complexing_agent",
  "gas_forming",
  "sequestering_agent",
  "sterilizing_agent",
  "esterifying_agent",
  "water_miscible_cosolvent",
  "crystallization_modifier_Inhibitor_sucrose",
  "stabilizer_for_freeze_dried_formulations",
  "blood_substitute_stabilizer",
  "channeling_agent",
  "osmotic_agent",
  "porosity_modifier",
  "blood_anticoagulant",
  "detergent",
  "water_holding",
  "cooling_agent",
  "pigment",
  "polishing_agent",
];
